### ISSUE TITLE
an error with version V0.3

### ISSUE THREAD

**Issue by bitcometz** [biowdl/QC#32]
Hello,
I git clone the QC version 0.3 and run with the following commands :
java -jar cromwell-41.jar run -i inputs.json QC.wdl

for the inputs.json:
{
  "QC.read1": "/Users/zhangjinbo/00.study/00.wdl/00.data/test_1.fastq.gz",
  "QC.read2": "/Users/zhangjinbo/00.study/00.wdl/00.data/test_2.fastq.gz",
  "QC.outputDir": "/Users/zhangjinbo/00.study/00.wdl/00.data/"
}

but I encounter with error informations:

**[error]** WorkflowManagerActor Workflow 270a91de-9576-4f21-8b20-e4d76ce70334 failed (during ExecutingWorkflowState): java.io.FileNotFoundException: Could not process output, file not found: 

/Users/00.study/00.wdl/00.data/QC/read2/fastqc/test_2_fastqc/summary.txt

And it seems that I have finished the fastqc:

Started analysis of ct_r1.fq.gz
Approx 100% complete for ct_r1.fq.gz
ln: /cromwell-executions/QC/36339686-7320-4509-bd8e-92f7cdea8569/call-qualityReportRead1/QualityReport/a852ddb8-e77b-46a8-b5dd-fa2013f6f53a/call-Fastqc/execution/glob-46825b46e945a63e406f2b396dd55704/adapter_content.png: Invalid cross-device link

Could you help with this problem? Thanks

Best

**Comment by bitcometz** [comment]
And the info in stderr.background: 
/bin/sh: can't open '/Users/00.study/00.wdl/QC_new/QC/cromwell-executions/QC/fad1ecd0-d642-4a92-b5c6-fd8070931089/call-Cutadapt/execution/script'

**Comment by rhpvorderman** [comment]
This is mostly a configuration issue.

This current QC pipeline still relies on the outputDir being mounted inside the docker container. So you have to make sure that this happens in your docker configuration. You can check the cromwell documation on how to configure cromwell. For docker make sure `docker run -v /Users/:/Users/` is somewhere in there.

With our current development pipeline this requirement we are working on dropping this requirement. You can not give a "QC.outputDir" input in the inputs. Instead you can set a `global_workflow_outputs_dir` in a `options.json` file. Checkout the cromwell documentation here: https://cromwell.readthedocs.io/en/stable/wf_options/Overview/#global-workflow-options. Using `use_relative_output_paths: true` is recommended.
Also it is important to set a docker_user to prevent permission problems.

A perfectly usable cromwell options file is available on this repo here: https://github.com/biowdl/QC/blob/BIOWDL-247/tests/cromwell_options.json

That way you do not need to use a docker configuration.
These changes will be merged into develop soon. 
After this has happened we will soon release a version 1.0 which will not require a docker configuration. Also we will make sure the documentation will be up to date for the 1.0 release.

Does this help?

**Comment by bitcometz** [comment]
Thanks! I try and get all the jobs done !
I'm so excited to see so many updates from you. I'm looking forward to it 

Best！！！

**Comment by rhpvorderman** [comment]
@bitcometz The pipeline should work fine now with the cromwell_options.json. It is merged in develop.
If you find any issues, please let us know. 
Thank you for using our pipelines!
